# -*- coding: utf-8 -*-
"""SSMBFINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GSMyPo77eV0_ovmiXxl9jQ_gytFBoOh0
"""

#Colab / Jupyter single cell

!pip install transformers accelerate gradio text-to-speech

from transformers import AutoModelForCausalLM, AutoTokenizer, set_seed
import torch
import gradio as gr
from text_to_speech import save as tts_save
import uuid

# Load the IBM Granite model from Hugging Face
model_name = "ibm-granite/granite-3.3-2b-instruct"  # as you specified
device = "cuda" if torch.cuda.is_available() else "cpu"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.bfloat16 if device == "cuda" else torch.float32,
)

def rewrite_with_tone(text, tone):
    """
    Rewrites `text` in the chosen `tone` using Granite model.
    We'll build a simple instruction prompt.
    """
    # Construct prompt
    prompt = (
        f"You are a helpful assistant. Rewrite the following text in a {tone} tone, "
        "while preserving its original meaning:\n\n"
        f"{text}\n\nRewritten:"
    )
    inputs = tokenizer(prompt, return_tensors="pt").to(device)
    set_seed(42)
    outputs = model.generate(
        **inputs,
        max_new_tokens= max(200, len(text) // 2),  # adjust as needed
        temperature=0.7,
        top_p=0.9,
    )
    rewritten = tokenizer.decode(outputs[0], skip_special_tokens=True)
    # Optionally remove the prompt part from rewritten (simple heuristic)
    # But because Granite uses an instruction-format, rewritten may directly be the answer
    return rewritten

def text_to_audio(text):
    """
    Converts text to audio. Uses `text-to-speech` library.
    Returns path to an mp3 file.
    """
    # Generate a random filename
    fname = f"/content/{uuid.uuid4().hex}.mp3"
    # Save TTS
    tts_save(text, "en", file=fname)
    return fname

def process(text, tone):
    if not text.strip():
        return "Please enter some text.", None, None
    # 1. Rewrite
    rewritten = rewrite_with_tone(text, tone)
    # 2. Convert to audio
    audio_path = text_to_audio(rewritten)
    # 3. For Gradio: return rewritten text, and audio file path
    return rewritten, "Here is your audio:", audio_path

# Build Gradio interface
with gr.Blocks(css="""
.gradio-container {
        background: #fff9c4;  /* light yellow */
    }
    .header {
        color: #000000;        /* black text color */

        text-align: center;
    }
 """) as demo:
    gr.Markdown("<h1 class='header'>📖🎙️ EchoVerse: AI Audiobook Generator🎧✨</h1>")
    inp = gr.Textbox(label="📝Input Text", lines=10, placeholder="💡Paste your text here …")
    tone = gr.Radio(["Neutral", "Suspenseful", "Inspiring"], label="Choose Tone", value="Neutral")
    btn = gr.Button("🎶Generate")
    out_text = gr.Textbox(label="✍️Rewritten Text", lines=10)
    out_audio = gr.Audio(label="🗣️Generated Audio", format="mp3")

    btn.click(fn=process, inputs=[inp, tone], outputs=[out_text, gr.Textbox(), out_audio])



demo.launch(share=True)

from huggingface_hub import login

login()  # It will ask you to paste your Hugging Face token